apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend1
  name: frontend1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend1
    spec:
      containers:
        - image: nginx:1.21
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
status: {}